apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb:latest
          volumeMounts:
            - name: smb
              mountPath: "/data"
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: scrapper